"use client";
import { useState,useMemo } from "react";
import { Inview } from "@/components/animation/springs/in-view";
import { Badge } from "@/components/ui/Badge";
import { activities,actTypeLabel,actTypeColor,actStatusLabel,type Activity,type ActType,type ActStatus } from "@/data/mocks/modules";
type View="list"|"calendar";
const STATUS_BADGE:Record<ActStatus,"teal"|"success"|"danger">={planned:"teal",completed:"success",cancelled:"danger"};
const TYPE_BADGE:Record<ActType,"teal"|"gold"|"success"|"danger"|"muted">={meeting:"teal",training:"gold",field:"success",report:"danger",workshop:"muted"};
function ActivityRow({act,delay}:{act:Activity;delay:number}){return <Inview tag="div" from={{opacity:0,y:12}} to={{opacity:1,y:0}} mode="once" config={{tension:220,friction:28}} delayIn={delay} className="flex items-center gap-4 px-5 py-4 border-b border-ivory-dk last:border-0"><div className="w-1 self-stretch rounded-badge" style={{background:actTypeColor[act.type]}}/><div className="flex-1 min-w-0"><p className="text-[0.875rem] font-semibold text-foreground m-0 truncate">{act.title}</p><p className="text-[0.75rem] text-muted m-0 mt-0.5">{act.date} — {act.time} · {act.location}</p><p className="text-[0.6875rem] text-muted m-0 mt-0.5">المشروع: {act.project} · {act.participants} مشارك</p></div><div className="flex flex-col gap-1.5 items-end"><Badge variant={TYPE_BADGE[act.type]}>{actTypeLabel[act.type]}</Badge><Badge variant={STATUS_BADGE[act.status]}>{actStatusLabel[act.status]}</Badge></div></Inview>}
function Section({title,count,children}:{title:string;count:number;children:React.ReactNode}){return <div><h3 className="font-display font-bold text-[0.9375rem] text-foreground mb-3">{title} <span className="text-[0.6875rem] text-muted">{count}</span></h3><div className="bg-white rounded-card border border-ivory-dk overflow-hidden">{children}</div></div>}
export function ActivitiesPage(){const [view,setView]=useState<View>("list");const [search,setSearch]=useState("");const [typeFilter,setTypeFilter]=useState<"all"|ActType>("all");const filtered=useMemo(()=>activities.filter(a=>(typeFilter==="all"||a.type===typeFilter)&&(!search||a.title.includes(search)||a.project.includes(search))),[typeFilter,search]);const planned=filtered.filter(a=>a.status==="planned"),completed=filtered.filter(a=>a.status==="completed"),cancelled=filtered.filter(a=>a.status==="cancelled");return <div dir="rtl" className="space-y-5"><div className="flex flex-wrap items-center gap-3"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="🔍 بحث..." className="flex-1 min-w-[12rem] px-3 py-2.5 rounded-btn border border-ivory-dk bg-white text-[0.875rem] outline-none"/><div className="flex gap-2 flex-wrap">{(["all","meeting","training","field","report","workshop"] as const).map(t=><button key={t} onClick={()=>setTypeFilter(t)} className="px-3 py-1.5 rounded-badge text-[0.75rem] font-semibold border cursor-pointer" style={{background:typeFilter===t?"var(--c-teal)":"transparent",color:typeFilter===t?"#fff":"var(--c-muted)"}}>{t==="all"?"الكل":actTypeLabel[t as ActType]}</button>)}</div><button onClick={()=>setView(view==="list"?"calendar":"list")} className="px-3 py-2 rounded-btn bg-ivory-dk border-0 cursor-pointer">{view==="list"?"▦ تقويم":"◉ قائمة"}</button></div>{view==="list"?<div className="space-y-5">{planned.length>0&&<Section title="الأنشطة المخططة" count={planned.length}>{planned.map((a,i)=><ActivityRow key={a.id} act={a} delay={i*60}/>)}</Section>}{completed.length>0&&<Section title="الأنشطة المنجزة" count={completed.length}>{completed.map((a,i)=><ActivityRow key={a.id} act={a} delay={i*60}/>)}</Section>}{cancelled.length>0&&<Section title="الأنشطة الملغاة" count={cancelled.length}>{cancelled.map((a,i)=><ActivityRow key={a.id} act={a} delay={i*60}/>)}</Section>}</div>:<div className="bg-white rounded-card border border-ivory-dk p-6"><h3 className="font-display font-bold">يونيو 2026</h3>{filtered.map(a=><ActivityRow key={a.id} act={a} delay={0}/>)}</div>}</div>}
